Refactor: optimization
glotaran/pyglotaran pull request #1060
Opened 2022-04-10 14:50 UTC by joernweissenborn

This completely overhauls the the package `glotaran.optimization`

### Change summary

- Removed `OptimizationGroupCalculator`
- created `DataProvider` to provide data for optimization
- created `MatrixProvider` to provide matrix caculations
- created `EstimationProvider` to provide clp and residuals
- created `Optimizer` class
- changed data alignment algorithm 
- added alignment methods `nearest`, `forward` and `backward`

### TODO

- include full models
- add mypy checks
- add docstrings

### Checklist

- [ ] ✔️ Passing the tests (mandatory for all PR's)
- [ ] 🚧 Added changes to changelog (mandatory for all PR's)
- [ ] 👌 Closes issue (mandatory for ✨ feature and 🩹 bug fix PR's)
- [ ] 🧪 Adds new tests for the feature (mandatory for ✨ feature and 🩹 bug fix PR's)
- [ ] 📚 Adds documentation of the feature

### Closes issues

closes #1003

2022-07-30 18:28 UTC, s-weigand commented
@joernweissenborn As discussed in slack and on the phone have a look at [🩹⌨️ Remove usage of 'Number' for typing](https://github.com/glotaran/pyglotaran/pull/1060/commits/ab97046a31e7469fbb43eb6a66c421a2b877ca63) and rename `index` to `global_index_value` where appropriate (or a different name when it isn't an int index)

2022-07-31 19:45 UTC, s-weigand requested changes
@joernweissenborn Thanks for all the work you put into refactoring the optimization package to make it more readable.

As usual, I got my nitpicks, sorry for that 😅

One of my biggest issues is that classes set attributes outside of the init method which makes it harder to read and also might cause errors if methods are not called in the proper order because the attribute would not exist in that case.

Personally, I think a functional approach makes things easier to unittest and is less error prawn than changing a mutable state, but ofc this also requires functions to take more arguments. 🤷‍♀️

2022-07-31 19:45 UTC, s-weigand commented on glotaran/optimization/matrix_provider.py
> +        return matrix
This is simple enough that we can use a pure numpy implementation which is actually faster

```python
In [1]: import numba as nb

In [2]: import numpy as np

In [3]: @nb.jit(nopython=True, parallel=True)
   ...: def apply_weight_nb(matrix, weight):
   ...:     matrix = matrix.copy()
   ...:     for i in nb.prange(matrix.shape[1]):
   ...:         matrix[:, i] *= weight
   ...:     return matrix
   ...:

In [4]: def apply_weight_np(matrix, weight):
   ...:     return (matrix.T * weight).T
   ...:

In [5]: matrix = np.ones((1000,200))

In [6]: weights = np.arange(1000)

In [7]: (apply_weight_nb(matrix,weights) == apply_weight_np(matrix,weights)).all()
Out[7]: True

In [8]: %timeit apply_weight_nb(matrix,weights)
749 µs ± 158 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [9]: %timeit apply_weight_np(matrix,weights)
134 µs ± 1.35 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [10]: %timeit apply_weight_nb(matrix,weights)
502 µs ± 20.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

2022-07-31 19:45 UTC, s-weigand commented on glotaran/optimization/test/test_constraints.py
> +    print("link_clp", link_clp, "index_dependent", index_dependent)  # T201
This is an artifact of a badly written noqa and a using `yesqa` see [this commit](https://github.com/glotaran/pyglotaran/commit/3c21f46d8c7a6ecfe5058cc2cc094cef5dd55cf2)

2022-07-31 19:45 UTC, s-weigand commented on setup.cfg
> +
This should be reactivated see [commit](https://github.com/glotaran/pyglotaran/commit/7b1d50725a0c7b31de04d018ab1654a496cde4c6)

2022-08-06 11:35 UTC, s-weigand commented
@joernweissenborn One more questing about typing, why do you use `np.typing.ArrayLike` instead of `np.ndarray`? Are the data a mix of `np.ndarray` and `xr.DataArray`?

2022-09-03 10:16 UTC, joernweissenborn commented on glotaran/model/dataset_group.py
> +        return len(set(global_dimensions)) == 1
done

2022-09-03 11:06 UTC, joernweissenborn commented
> @joernweissenborn One more questing about typing, why do you use `np.typing.ArrayLike` instead of `np.ndarray`? Are the data a mix of `np.ndarray` and `xr.DataArray`?

I like to keep the interface abstract so we later might use e.g. dask or gpu containers.

2022-09-03 11:19 UTC, joernweissenborn commented on glotaran/optimization/matrix_provider.py
> +"""Module containing the matrix provider classes."""
Sometimes this has to be done this way. But this classes will always just do init -> claculate -> get_result. Many of the steps are not easily unit testable anyway.

2022-09-04 22:19 UTC, s-weigand approved these changes
Looks good now, thnx 😄

2022-09-04 22:41 UTC, jsnel commented
I looked in more detail at the remaining discrepancy in the results for the `simultaneous_analysis_6d_disp` integration test and found that the results (estimated parameters) in this PR are *closer* to the true values (values simulated and estimated in TIM as provided by @ism200), so we consider this a regression for the better and accept the change. This mean we will have to re-create the gold standard from the code at the point of this merged PR. 

Spreadsheet with evidence attached: 
[optimized_parameters-6d-compare-PR1118-main-to-PR1060-to-TIM.xlsx](https://github.com/glotaran/pyglotaran/files/9485627/optimized_parameters-6d-compare-PR1118-main-to-PR1060-to-TIM.xlsx)

2022-09-04 22:43 UTC, jsnel submitted a review, later dismissed
Reviewed ok! See comments for in depth investigation on changes in integration test results.

2022-09-04 22:54 UTC, s-weigand commented
After [updating the examples to raise the `maximum_number_function_evaluations` for the `ex_two_datasets` from 15 to 18](https://github.com/glotaran/pyglotaran-examples/pull/72) we only have failing comparison tests for `simultaneous_analysis_6d_disp` as [explained by @jsnel ](https://github.com/glotaran/pyglotaran/pull/1060#issuecomment-1236428361)
See [CI run 1901](https://github.com/glotaran/pyglotaran/runs/8179855527?check_suite_focus=true) or attached logs 
[PR1060-CI-run-1901.zip](https://github.com/glotaran/pyglotaran/files/9485635/PR1060-CI-run-1901.zip)

We will now update the 'gold standard' and run the CI again

2022-09-04 23:45 UTC, jsnel submitted a review, later dismissed

2022-09-04 23:52 UTC, jsnel approved these changes

2022-09-04 23:59 UTC, merged