Refactor/optimization
glotaran/pyglotaran pull request #442
Opened 2020-11-20 14:59 UTC by joernweissenborn

This PR fill Refactor the Analysis backage and superceds feature/399

2020-11-20 15:59 UTC, s-weigand commented
Since this is based on `feature/399`, could you make a PR for that first, and rebase this branch on master after merging?
Especially since @jsnel did some work on `feature/399` this would simplify the reviewing process.

Quick sidenotes:
- `typing.<type_name>` doesn't provide any advantage and using `from typing import <type_name>` leads to a better readability
- There is a new and better way to define namedtuples, which allows typing the slots and providing default values
  Old way:
  ```python 
  from collections import namedtuple
  MyNamedTuple= namedtuple("MyNamedTuple", "slot1 slot2")
  ```
  New way (`python >= 3.6.1`)
  ```python 
  from typing import NamedTuple
  class MyNamedtuple(NamedTuple):
      slot1: int
      slot2: str = "default value"
  ```

- Custom errors
  As per naming convention
  ```python
  ParameterError = ValueError("Parameter not initialized")
  ```
  Should be 
  ```python
  parameter_error = ValueError("Parameter not initialized")
  ```
  Since it's an instance and not a class.
  A proper custom error  would look like this
  ```python
  class ParameterError(ValueError):
      def __init__(self):
           super().__init__("Parameter not initialized")
  ```
  That way the traceback will actually show `ParameterError` and not just `ValueError`.

  Also, this is more flexible since you could use string formatting, e.g. [see](https://github.com/s-weigand/flake8-nb/blob/3db7eb93b224cf663a53f31a3f1338850253708c/flake8_nb/parsers/cell_parsers.py#L35-L56 )

2020-11-20 21:04 UTC, s-weigand requested changes
See https://github.com/glotaran/pyglotaran/pull/442#issuecomment-731253232

2020-11-21 21:09 UTC, s-weigand commented on glotaran/analysis/residual_calculation.py
> +        for i, index in enumerate(global_axis):
Using `enumerate` and NOT using index doesn't make sense. Also, it is a code smell.

2020-11-21 21:09 UTC, s-weigand commented on glotaran/analysis/residual_calculation.py
> +        for i, index in enumerate(global_axis):
Using `enumerate` and NOT using index doesn't make sense. Also, it is a code smell.

2020-11-21 21:22 UTC, s-weigand commented on glotaran/analysis/residual_calculation.py
> +        for i, index in enumerate(global_axis):
Opps this was intended for #413

2020-11-21 21:22 UTC, s-weigand commented on glotaran/analysis/residual_calculation.py
> +        for i, index in enumerate(global_axis):
Opps this was intended for #413

2020-11-23 00:08 UTC, s-weigand commented
I rebased the PR for you, but QA tests are failing since as of #445 we don't allow changes which decrease code documentation.
Check the [new docstring section](https://pyglotaran.readthedocs.io/en/latest/contributing.html#docstrings) for help on how documentation should look like and which tools you can use.

2020-11-25 11:40 UTC, s-weigand commented
For type checking you can use
```console
$ mypy  --ignore-missing-imports --scripts-are-modules glotaran/analysis/problem.py
```

2020-11-25 12:37 UTC, s-weigand commented
Also, please us a [`postponed annotations`](https://stackoverflow.com/a/61544901/3990615) pattern ([see](https://github.com/glotaran/pyglotaran/pull/453/files#diff-fc1e7b8e8325d1d3f6573de23fbad4f4b7e5d375940355abc0731ed14c5100bd)), to prevent circular dependencies.

All imports that are only used for typing should be inside an `if TYPE_CHECKING:` block.
This will also improve performance since the imports don't need to be done at runtime.

2020-11-26 16:07 UTC, s-weigand requested changes

2020-11-26 16:07 UTC, s-weigand commented on glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_result.py
> +T_Problem = typing.TypeVar("glotaran.analysis.problem.Problem")
This will cause 'not valid as a type' see #456 for a reference how it should be done.

2020-11-26 16:16 UTC, s-weigand requested changes

2020-11-26 16:16 UTC, s-weigand commented on glotaran/analysis/problem.py
> +T_Model = typing.TypeVar("glotaran.model.Model")
This will cause 'not valid as a type' see #456 for a reference how it should be done.

2020-11-26 18:41 UTC, s-weigand commented on glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_result.py
> +T_Problem = typing.TypeVar("glotaran.analysis.problem.Problem")
I fixed this one myself after rebasing

2020-11-27 10:36 UTC, s-weigand commented
A sidenote on typing with classes:
- `MyClass` refers to an instance of `MyClass` or a subclass of it, same as `isinstance`
- `Type[Myclass]` refers to the `MyClass` or a subclass of it directly and is incompatible with instances of it

2020-12-01 22:56 UTC, jsnel approved these changes
All approved - looked at all changes individually as well.
Personally resolved any merge conflicts. 
Good to go.
BusFactor++

2020-12-01 22:56 UTC, s-weigand approved these changes
Just trusting @jsnel 's review at this 😄

2020-12-01 22:59 UTC, merged