🩹 Fix calculation of 'lorentzian-bandshape'
glotaran/pyglotaran pull request #686
Opened 2021-06-05 18:54 UTC by s-weigand

This PR changes the implementation of the `lorentzian-bandshape` calculation to use a `1/cm` instead of an `nm` axis.

Thus the `location` and `width` now also need to be provided in `1/cm`.

**Testing**

Passing the tests is mandatory.

**Closing issues**

closes #685

2021-06-05 22:29 UTC, s-weigand commented
Maybe we should also rename `location` to `center`, so it is consistent with the naming for Gaussians (e.g. used for the IRF).

2021-06-06 09:28 UTC, ism200 commented
Dear all,

With a skewed Gaussian (the spectral shape that is used most often) it is better to call it the location (of the maximum) parameter.

Regards,

ivo

Van: Sebastian Weigand ***@***.***>
Verzonden: zondag 6 juni 2021 00:29
Aan: glotaran/pyglotaran ***@***.***>
CC: Stokkum, I.H.M. van ***@***.***>; Review requested ***@***.***>
Onderwerp: Re: [glotaran/pyglotaran] 🩹 Fix calculation of 'lorentzian-bandshape' (#686)


Maybe we should also rename location to center, so it is consistent with the naming for Gaussians (e.g. used for the IRF).

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/glotaran/pyglotaran/pull/686#issuecomment-855304327>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEOZEE462MYQJQO5ODVXESDTRKQMDANCNFSM46E36PHA>.

2021-06-06 20:07 UTC, jsnel requested changes
Given the current implementation follows the (skewed/unskewed) *Gaussian* implementation of TIMP (DOI: [10.18637/jss.v018.i03](http://dx.doi.org/10.18637/jss.v018.i03) page 29, 31-36, it would make more sense to rename the class accordingly. 
The TIMP paper, page 29, hints at possible other implementations:

> The spectral bandshapes are typically described in terms of a linear superposition of standard band shapes (e.g., Gaussian, Lorentzian, Voigt, skewed Gaussian) or in terms of splines.

2021-06-08 00:16 UTC, jsnel approved these changes
Renamed lorentzian to (skewed) gaussian
Addressed a (major) deprecation warning in xarray which would have resulted in an error in 0.19.0

2021-06-08 00:26 UTC, merged