Add include statement to model yml
glotaran/pyglotaran pull request #930
Opened 2021-12-03 17:17 UTC by joernweissenborn

This PR adds the statement `include` to the model spec. This useful for splitting large models into multiple files.

### Change summary

- added `include` keyword to model spec yaml and added parsing logic
- this might have troubles when round tripping, so more work on that is required

### Checklist

- [ ] ✔️ Passing the tests (mandatory for all PR's)
- [ ] 👌 Closes issue (mandatory for ✨ feature and 🩹 bug fix PR's)
- [ ] 🧪 Adds new tests for the feature (mandatory for ✨ feature and 🩹 bug fix PR's)
- [ ] 📚 Adds documentation of the feature

### Closes issues

closes #XXXX

2021-12-03 17:21 UTC, jsnel commented
@s-weigand please review and consider how this may interact with the roundtrip support recently introduced by switching to ruaml for yaml parsing: https://github.com/glotaran/pyglotaran/pull/893

2021-12-03 18:52 UTC, s-weigand requested changes
I know this is just the first quick and dirty implementation, but I think the way it is atm it will cause more problems than it solves.
In general, a feature like this is very useful to split up logic, one could even imagine a kind of database with known megacomplexes users can just use to build their model.

Using a YAML tag (`!include`) would give us more flexibility, e.g. see this dated answer from the `ruaml` Author
https://stackoverflow.com/a/44913652/3990615

In any case we need to better handle users accidentally overwriting parts of their specs!

As for round trip support, this will need some investigation and extra work in any case since the ruaml updating doesn't support direct updating from dict w/o loosing all comments.

2021-12-03 18:52 UTC, s-weigand commented on glotaran/builtin/io/yml/test/test_model_include.py
> +        f.write(TEST_MODEL.format(d_path=d_path, m_path=m_path))
Writing to file could be done by using `Path.write_text` (which internally also uses a context manager).

2021-12-03 18:52 UTC, s-weigand commented on glotaran/builtin/io/yml/yml.py
> +                spec.update(self._load_yml(include))
We should check if there are duplicated entries and at least warn users if they are going to be overwritten.
Atm, we just overwrite things by order, and even more dangerous we overwrite at the top level! 
Image the following scenario:
A user defines each megacomplex in its own file and includes both, all but the last one get overwritten without any warning.

```python
In [1]: spec = {"megacomplex": {"m1": {"foo":1}}}

In [2]: mc_include = {"megacomplex": {"m2": {"bar":2}}}

In [3]: spec.update(mc_include)

In [4]: spec
Out[4]: {'megacomplex': {'m2': {'bar': 2}}}
```

2022-01-16 01:32 UTC, s-weigand commented
Closing in favor #955

2022-01-16 01:32 UTC, closed without merging